version: '3'
services:
   jupyter:
      build: .
      container_name: jupyter
      ports:
         - 8888:8888
         - 4040:4040
         - 4041:4041
      volumes:
         - ./:/home/jovyan/work
      environment:
         - JUPYTER_ENABLE_LAB=yes
         - RESTARTABLE=yes
